### ISSUE TITLE
Create Acceptance criteria

### ISSUE THREAD

**Issue by msdale** [msdale/caffiene-overflow#1]
use the I WANT and THEN format to create acceptance criteria

**Comment by alexisn84** [comment]
GIVEN a item search with form inputs
WHEN I search for an item
THEN I am presented with current pricing at available retailers
WHEN I view the retailer comparisons
THEN I am presented with the item name, description, image and price and button to add shopping list
WHEN I click add to shopping list button the item is stored in local store
THEN I can click on a button to take me to view shopping lists
WHEN I click on button to view shopping lists I am taken to a new page that shows each retailer and their items in their own list
THEN I am presented with options to delete items, delete entire list or print list
WHEN I click on the corresponding button to delete an item, that single item is cleared from the list and local storage
WHEN I click on delete list, the entire list for that retailer will by cleared from the list and local storage
THEN I am presented a button to return to the main page to continue search
